Makes sleepers buildable and adds them to the research techweb
Willardstation/tg-voidcrew pull request #22
Opened 2022-08-20 22:15 UTC by FernandoJ8

## About The Pull Request

Sleepers can now be built and deconstructed like a normal machine, as well as having their own research node that makes them printable at a medical lathe.

## Why It's Good For The Game

Closes #6, sleepers being available in-round is cool and fits a more combat-focused style.

## Changelog

:cl:
add: Sleepers can now be built and deconstructed. A research node has been also added that makes the boards printable at a medical lathe.
/:cl:

2022-08-20 22:17 UTC, FernandoJ8 commented
We're not actually doing changelogs, are we?

2022-08-21 03:03 UTC, san7890 commented
> We're not actually doing changelogs, are we?

i think we should tbh

2022-08-21 03:04 UTC, san7890 requested changes

2022-08-21 03:04 UTC, san7890 commented on code/modules/research/designs/machine_designs.dm
> +	desc = "The circuit board for a sleeper unit"
```suggestion
	desc = "The circuit board for a sleeper unit."
```

2022-08-24 10:59 UTC, JohnFulpWillard reviewed
deconstructing a stasis unit needs to drop the board

2022-08-24 11:00 UTC, JohnFulpWillard commented
> > We're not actually doing changelogs, are we?
> 
> i think we should tbh

it will get overwriten when we update to latest TG

2022-08-24 14:43 UTC, FernandoJ8 commented
> deconstructing a stasis unit needs to drop the board


> deconstructing a stasis unit needs to drop the board

The sleeper board? Why?

2022-08-30 03:11 UTC, merged